GuitarShop/Controllers/ContactController.cs
using GuitarShop.Models;
using GuitarShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactRepository _contactRepository;

        public ContactController(IContactRepository contactRepository) => _contactRepository = contactRepository;



        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            if (ModelState.IsValid)
            {
                _contactRepository.AddContact(contact);
                return RedirectToAction("ContactComplete");
            }
            return View(contact);

        }


        public IActionResult ContactComplete()
        {
            return View();
        }
    }
}

GuitarShop/Controllers/GuitarController.cs
using System.Collections.Generic;
using GuitarShop.Models;
using GuitarShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    public class GuitarController : Controller
    {
        private readonly IGuitarInventory _guitarInventory;

        public GuitarController(IGuitarInventory guitarInventory) => _guitarInventory = guitarInventory;


        /// <summary>
        /// Action method GET.
        /// </summary>
        /// <returns>View page with the list of all the guitars.</returns>
        public IActionResult Index()
        {
            var guitars = _guitarInventory.GetAllGuitars();
            if (guitars != null)
            {
                return View(guitars);
            }
            return NotFound();
        }


        /// <summary>
        /// Action method GET that searches for guitars that matches with the ones in the guitars inventory.
        /// </summary>
        /// <returns>View page with the search of guitars form.</returns>
        public IActionResult Search()
        {
            return View();
        }


        /// <summary>
        /// Action method POST that takes as parameters the fields completed by the user and bind them with the inventory guitars.
        /// </summary>
        /// <param name="guitars"></param>
        /// <returns>
        /// View page with the list of matching guitars or with a validation error message in case of wrong input.
        /// </returns>
        [HttpPost]
        public IActionResult MatchingGuitarsAfterSearch([Bind("Builder,Model,Type,BackWood,TopWood")] GuitarSpecification guitars)
        {
            var matchingGuitars = new List<Guitar>();

            if (ModelState.IsValid)
            {
                if (guitars != null)
                {
                    matchingGuitars = _guitarInventory.Search(guitars);
                    if (matchingGuitars.Count != 0)
                    {
                        return View(matchingGuitars);
                    }
                    else
                    {
                        return RedirectToAction(nameof(NoMatchingGuitarsAfterSearch));
                    }
                }
                else
                {
                    return NotFound();
                }

            }
            return RedirectToAction(nameof(Search));
        }


        /// <summary>
        /// Action method GET invoked only if there is no matching guitars with the input form entered by the user.
        /// </summary>
        /// <returns>View page with a message for user.</returns>
        public IActionResult NoMatchingGuitarsAfterSearch()
        {
            return View();
        }

        /// <summary>
        /// Action method GET invoked when the user what to see the details of a guitar, from the guitars inventory, that matches with the id introduced as parameter.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View page with matching guitar.</returns>
        public IActionResult Details(int id)
        {
            var guitar = _guitarInventory.GetGuitarById(id);
            if (guitar == null)
            {
                return NotFound();
            }
            return View(guitar);
        }


    }
}

GuitarShop/Controllers/ShoppingCartController.cs
using System.Collections.Generic;
using System.Linq;
using GuitarShop.Models;
using GuitarShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly IGuitarInventory _guitarInventory;


        public ShoppingCartController(IGuitarInventory guitarInventory)
        {
            _guitarInventory = guitarInventory;
        }


        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Guitar.Price * item.Quantity);
            return View();
        }

        /// <summary>
        /// Action method GET invoked when the user chooses to buy a guitar, in the current session.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>The View page with the new guitar added to a list of shopping cart guitars.</returns>
        public IActionResult AddToShoppingCart(int id)
        {
            var guitar = _guitarInventory.GetGuitarById(id);
            if (guitar == null) return NotFound();

            if (SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart") == null)
            {
                var cart = new List<ShoppingCartItem>();
                cart.Add(new ShoppingCartItem { Guitar = guitar, Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");

                if (IsGuitarExitingInShoppingCart(id))
                {
                    int index = GetIndexForShoppingCartGuitar(id);
                    if (index != -1)
                    {
                        cart[index].Quantity++;
                    }
                }
                else
                {
                    cart.Add(new ShoppingCartItem { Guitar = guitar, Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction(nameof(Index));
        }


        // Action method GET invoked when the user wants to delete a guitar from the ShoppingCart
        public IActionResult Delete(int id)
        {
            var guitar = _guitarInventory.GetGuitarById(id);
            if (guitar != null)
            {
                return View(guitar);
            }
            return NotFound();
        }

        // Action method POST invoked after confirmation that the guitar selected can be deleted from the ShoppingCart.
        [HttpPost]
        public IActionResult ConfirmedDelete(int id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");

            if (IsGuitarExitingInShoppingCart(id))
            {
                int index = GetIndexForShoppingCartGuitar(id);
                if (index != -1)
                {
                    cart.RemoveAt(index);
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                }
            }
            return RedirectToAction(nameof(Index));
        }


        // Method invoked to verify if there is any guitar in the Shopping Cart in the current session.
        private bool IsGuitarExitingInShoppingCart(int id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; ++i)
            {
                if (cart[i].Guitar.Id == id)
                {
                    return true;
                }

            }
            return false;
        }

        // Method invoked to take the index of the guitar from the Shopping Cart in the current session that has the same Id with the guitar Id introduced as parameter.
        private int GetIndexForShoppingCartGuitar(int id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");

            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Guitar.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

GuitarShop/Controllers/WishListController.cs
using System.Collections.Generic;
using GuitarShop.Models;
using GuitarShop.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace GuitarShop.Controllers
{
    public class WishListController : Controller
    {
        private readonly IGuitarInventory _guitarInventory;


        public WishListController(IGuitarInventory guitarInventory)
        {
            _guitarInventory = guitarInventory;
        }

        public IActionResult Index()
        {
            var wishList = SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList");
            ViewBag.wishList = wishList;
            return View();

        }


        /// <summary>
        /// Action method GET invoked when the user chooses as favorite a guitar, in the current session.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>The View page with the new favorite guitar added to a list of favorite guitars.</returns>
        public IActionResult AddToWishList(int id)
        {
            var guitar = _guitarInventory.GetGuitarById(id);
            if (guitar == null) return NotFound();


            if (SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList") == null)
            {
                var wishList = new List<WishListItem>();
                wishList.Add(new WishListItem { Guitar = guitar });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "wishList", wishList);
            }
            else
            {
                var getWishList = SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList");

                if (IsGuitarExitingInWishList(id))
                {
                    return RedirectToAction(nameof(Index));
                }
                var wishList = SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList");
                wishList.Add(new WishListItem { Guitar = guitar });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "wishList", wishList);
            }

            return RedirectToAction(nameof(Index));
        }



        // Action method GET invoked when the user wants to delete a guitar from the WishList
        public IActionResult Delete(int id)
        {
            var guitar = _guitarInventory.GetGuitarById(id);
            if (guitar != null)
            {
                return View(guitar);
            }
            return NotFound();
        }


        // Action method POST invoked after confirmation that the guitar selected can be deleted from the WishList.
        [HttpPost]
        public IActionResult ConfirmedDelete(int id)
        {
            var wishList = SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList");

            if (IsGuitarExitingInWishList(id))
            {
                int index = GetIndexForWishListGuitar(id);
                if (index != -1)
                {
                    wishList.RemoveAt(index);
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "wishList", wishList);
                }
            }
            return RedirectToAction(nameof(Index));
        }


        // Method invoked to verify if there is any guitar in the WishList in the current session.
        private bool IsGuitarExitingInWishList(int id)
        {
            var wishList = SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList");
            for (int i = 0; i < wishList.Count; ++i)
            {
                if (wishList[i].Guitar.Id == id)
                {
                    return true;
                }
            }
            return false;
        }

        // Method invoked to take the index of the guitar from the WishList in the current session that has the same Id with the guitar Id introduced as parameter.
        private int GetIndexForWishListGuitar(int id)
        {
            var wishList = SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContext.Session, "wishList");

            for (int i = 0; i < wishList.Count; i++)
            {
                if (wishList[i].Guitar.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }

}

GuitarShop/Views/Shared/_Footer.cshtml
<!-- Footer Section -->
<footer class="text-center" style="background-color: #2d2d30; color: #f5f5f5; padding: 20px;">
    <p class="text-center"><a href="#"><span class="glyphicon glyphicon-chevron-up" data-toggle="tooltip" title="BACK TO TOP"></span></a></p>
    <p>Made by Oana Ujica:<a href="https://codingwithoana.wordpress.com/" data-toggle="tooltip" title="Visit www.codingwithoana.wordpress.com" target="_blank" style="color:darkgoldenrod">   www.codingwithoana.wordpress.com</a></p>
</footer>

GuitarShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Guitar Shop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="~/content/site.css" />
</head>
<body style="background-color:whitesmoke;">

    <!-- Navigation Bar Section -->
    <partial name="~/Views/Shared/_NavigationBar.cshtml" />


    <!-- Body Section -->
    <div>
        @RenderBody()
    </div>


    <!-- Footer Section -->
    <partial name="~/Views/Shared/_Footer.cshtml" />

</body>
</html>

GuitarShop/Views/Shared/_NavigationBar.cshtml
@using GuitarShop.Services
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!-- Navigation Bar Section -->
<nav class="navbar navbar-inverse navbar-fixed-top" style="letter-spacing: 4px;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">GUITAR SHOP</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home"></span> HOME</a></li>
                <li><a asp-controller="Guitar" asp-action="Index"><span class="glyphicon glyphicon-th-list"></span> OUR GUITARS</a></li>

                @if (SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContextAccessor.HttpContext.Session, "wishList") != null)
                {
                    <li><a asp-controller="WishList" asp-action="Index"><span class="glyphicon glyphicon-heart-empty"></span> WISHLIST</a></li>
                }

                @if (SessionHelper.GetObjectFromJson<List<WishListItem>>(HttpContextAccessor.HttpContext.Session, "cart") != null)
                {
                    <li><a asp-controller="ShoppingCart" asp-action="Index"><span class="glyphicon glyphicon-shopping-cart"></span> SHOPPING CART</a></li>
                }

                <li><a asp-controller="Guitar" asp-action="Search"><span class="glyphicon glyphicon-search"></span> SEARCH</a></li>
                <li><a asp-controller="Contact" asp-action="Index"><span class="glyphicon glyphicon-info-sign"></span> CONTACT</a></li>
            </ul>
        </div>
    </div>
</nav>